# Generated by Django 3.1 on 2022-08-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220816_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcategory',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
