# Generated by Django 3.1 on 2022-08-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220816_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationCategory',
        ),
    ]
