# Generated by Django 3.1 on 2022-08-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_variationcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationCategory',
        ),
    ]
