# Generated by Django 3.1 on 2022-08-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_variationcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcategory',
            name='variation',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variationcategory'),
        ),
    ]
