# Generated by Django 3.1 on 2022-08-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220816_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variationcategory'),
        ),
    ]
