# Generated by Django 3.1 on 2022-08-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220817_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='VariationValue',
        ),
    ]
