# Generated by Django 3.1 on 2022-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220829_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='attachment',
            field=models.ImageField(default='default/default.png', upload_to='photos/variations'),
        ),
    ]
