# Generated by Django 3.1 on 2022-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20220829_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
