# Generated by Django 3.1 on 2022-08-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220829_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationvalue',
            name='attachment',
        ),
    ]
