# Generated by Django 3.1 on 2022-08-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220817_1712'),
        ('carts', '0007_auto_20220824_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.VariationValue'),
        ),
    ]
