# Generated by Django 3.1 on 2022-08-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220824_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
